- name: Configure web server
  hosts: button-click-server
  become: true
  tasks:
    - name: Install NGINX
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: Create site directory
      ansible.builtin.file:
        path: /usr/share/www/
        state: directory
    - name: Copy site files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/usr/share/www/{{ item }}"
      loop:
        - index.html
        - style.css
        - script.js
    - name: Copy site config
      ansible.builtin.copy:
        src: button-click.conf
        dest: /etc/nginx/conf.d/button-click.conf
    - name: Copy certificate files
        src: ".github/{{ item }}"
        dest: "/root/{{ item }}"
        mode: preserve
      loop:
        - cert-chain
        - cert-key
    - name: Run NGINX
      ansible.builtin.systemd_service:
        name: nginx
        state: reloaded
        enabled: true

- name: Update DNS
  hosts: button-click-server
  tasks:
    - name: Create DNS directory
      ansible.builtin.file:
        path: dns/
        state: directory
    - name: Copy token and update script
      ansible.builtin.copy:
        src: ".github/{{ item }}"
        dest: "dns/{{ item }}"
        mode: preserve
      loop:
        - set-dns-token.sh
        - update-dns.sh
    - name: Run DNS update
      ansible.builtin.shell:
        chdir: dns/
        cmd: source ./set-dns-token.sh && ./update-dns.sh
