---
name: Perform code checks
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Terraform
        run: |
          .github/setup-hashicorp-apt-repo.sh
          sudo apt-get install terraform
      - name: Run Terraform format check
        run: terraform fmt -check
      - name: Run YAMLLint
        run: yamllint --format github --strict .
      - name: Install NPM modules
        run: npm install
      - name: Run ESLint
        run: ./node_modules/.bin/eslint
