---
name: Perform code checks
on: push  # yamllint disable-line rule:truthy
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Terraform and ShellCheck
        run: |
          .github/setup-hashicorp-apt-repo.sh
          sudo apt-get install terraform shellcheck
      - name: Run Terraform format check
        run: terraform fmt -check
      - name: Install shfmt
        run: curl --show-error --silent https://webi.sh/shfmt | sh
      - name: Run ShellCheck
        run: shfmt --find . | xargs shellcheck
      - name: Run YAMLLint
        run: yamllint --format github --strict .
      - name: Install NPM modules
        run: npm install
      - name: Run ESLint
        run: ./node_modules/.bin/eslint
