name: Configure Server
on: push
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible
      - name: Setup SSH Access
        run: |
          cat "${{ secrets.SERVER_HOST_KEYS }}" >>~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add <(echo "${{ secrets.INFRA_ACCESS_KEY }}")
      - name: Run Playbook
        run: |
          ansible-playbook --inventory ./inventory.yml ./playbook.yml
      - name: Cleanup SSH Access
        run: |
          ssh-keygen -R sudhartion.duckdns.org
          pkill ssh-agent
