name: Configure Server
on:
  workflow_run:
    workflows: [Configure Infrastructure]
    types: [completed]
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible
      - name: Setup SSH Access
        id: setup-ssh-access
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SERVER_HOST_KEYS }}" >>~/.ssh/known_hosts
          eval $(ssh-agent)
          echo "ssh_auth_sock=${SSH_AUTH_SOCK}" >>"${GITHUB_OUTPUT}"
          echo "ssh_agent_pid=${SSH_AGENT_PID}" >>"${GITHUB_OUTPUT}"
          ssh-add <(echo "${{ secrets.INFRA_ACCESS_KEY }}")
      - name: Run Playbook
        env:
          SSH_AUTH_SOCK: "${{ steps.setup-ssh-access.outputs.ssh_auth_sock }}"
        run: |
          ansible-playbook --inventory ./inventory.yml ./playbook.yml
      - name: Cleanup SSH Access
        env:
          SSH_AGENT_PID: "${{ steps.setup-ssh-access.outputs.ssh_agent_pid }}"
        run: |
          ssh-keygen -R sudhartion.duckdns.org
          kill "${SSH_AGENT_PID}"
